# fly.toml app configuration file generated for loc-express-test on 2023-08-17T21:32:25+09:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "loc-express-test"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
